name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Zig
        run: brew update && brew install zig

      - name: Build
        run: zig build

      - name: Run tests
        run: zig build test
